[tox]
envlist =
    py310-django{42, 52}
    py311-django{42, 52}
    py312-django{42, 52, 60}
    py313-django{52, 60}
    py314-django{52, 60}
    py314-djangomain

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
setenv = COVERAGE_FILE=.coverage.{envname}
passenv =
    CLAMD_USE_TCP
    CLAMD_TCP_SOCKET
commands = python -Wdefault -m pytest --cov --cov-report term-missing:skip-covered src/django_clamd/tests/test.py
deps =
    pytest
    pytest-cov
    django42: django~=4.2.0
    django52: django~=5.2.0
    django60: django~=6.0.0
    djangomain: https://github.com/django/django/archive/refs/heads/main.zip

ignore_outcome =
    djangomain: true
